# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'meetcute_app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for meetcute_app
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  target 'meetcute_app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'meetcute_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

end